### ISSUE TITLE
Missing dependencies jndi and jta

### ISSUE THREAD

**Issue by sjahreis** [linked-planet/atlassian-plugin-kotlin#9]
**Describe the bug**
The dependencies `jndi:jndi:1.2.1` and `jta:jta:1.0.1` are not available within the central maven or the atlassian repos. Those missing libraries are available within a regular Confluence/Jira where the plugin might be deployed to but not within the development instance which is created using Maven during the build. Those missing dependencies can cause debugging-problems.

**To Reproduce**
1. Start the maven goal jira:run in IntelliJ
2. Within the Run tab wait until the run step shows error messages about not finding those deps

**Expected behavior**
No missing dependencies.

**Screenshots**
![image](https://user-images.githubusercontent.com/7789790/144629503-4af80c47-5f10-40a9-86e1-64b39a56927d.png)

**Comment by weickmanna** [comment]
@sjahreis I just created a fresh project from the new archetype version 3.3.0.
I imported it into IntelliJ and started the jira:debug run configuration.
I don't get these errors anymore. Maybe this problem is resolved by now? We had some Jira upgrades and also AMPS upgrade.

**Comment by sjahreis** [comment]
I still get the error starting a fresh 3.0.3 Jira project.
![image](https://user-images.githubusercontent.com/7789790/201613315-27cfe3ac-10ca-401b-8dde-60ae9b561549.png)
